spring:
  application:
    name: cibil-error-monitor
  kafka:
    bootstrap-servers: kafka:9092
    streams:
      application-id: cibil-error-monitor-app
      properties:
        commit.interval.ms: 1000
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  datasource:
    url: jdbc:oracle:thin:@//oracle-xe:1521/XEPDB1
    username: amit
    password: Welcome123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

logging:
  level:
    root: INFO
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  show-details: when-authorized

app:
  circuit:
    threshold:
      error-rate: 50.0
      min-total: 10
    reset:
      interval-minutes: 15
      error-rate: 5.0
      min-total: 10
  kafka:
    error-topic: error-monitor-events
