spring:
  application:
    name: cibil-error-monitor
  kafka:
    bootstrap-servers: kafka-kafka-1:9092
    streams:
      application-id: cibil-error-monitor-app
      properties:
        commit.interval.ms: 1000

  datasource:
    url: jdbc:oracle:thin:@//oracle-xe:1521/XEPDB1
    username: amit
    password: Welcome123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

logging:
  level:
    root: INFO
    com.example: DEBUG
