-- circuitbreaker_status table
CREATE TABLE circuitbreaker_status (
  seqnum NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  flag   CHAR(1) DEFAULT 'N' NOT NULL,
  timestamp TIMESTAMP
);

-- error_stats table
CREATE TABLE error_stats (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  total_message NUMBER,
  error_count NUMBER,
  error_rate NUMBER(5,2),
  created_time TIMESTAMP
);

-- Optional: enforce uniqueness so only one row per minute (enable manually if desired)
-- CREATE UNIQUE INDEX ux_error_stats_start_time ON error_stats(start_time);
